steps:
  build:
    image: node:20-alpine
    when:
      event: manual
    commands:
      - npm ci
      - npm run build
      - npm test || true

  build-development:
    image: node:20-alpine
    when:
      branch: develop
      event: push
    commands:
      - npm ci
      - npm run build
      - npm test || true

  build-production:
    image: node:20-alpine
    when:
      branch: develop
      event: tag
      ref: refs/tags/v*
    commands:
      - npm ci
      - npm run build
      - npm test

  npm-publish:
    image: node:20-alpine
    when:
      branch: develop
      event: tag
      ref: refs/tags/v*
    secrets:
      - npm_token
    commands:
      - npm ci
      - npm run build
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - npm publish --access public
